Configuration
 ( Version "2.1"
   Date "2026-09-22-09:39:58.972"
   Name "GC_RVS" )
ProgramUnits
 (
   Program
    ( Name "AnyTypeLocVar"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "AnyTypeParam"
      Directory "probes"
      MainProgram False )
   Library
    ( Name "AuxLib"
      Directory "probes" )
   Program
    ( Name "BadBareDurStr"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadBareTimeStr"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadBuiltinDatatype"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadBuiltinOutArg"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadBuiltinWrong"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadConsecSeqSteps"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadConstVarAs"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadCrossMod"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDatatypeShadows"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupDatatypeName"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupModTypeName"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupRecFldName"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupSfcElemNames"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupSibSubmods"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDupVariaNames"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadDurLit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadEncodingStress"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadFreeCmtInMod"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadGraphObjDouble"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadInitValType"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadMalformed"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadModCodeWithMod"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadNotSattLine"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadOldNewOnNon"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadOldNewOnNonB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadOversizeInput"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadSeqForkUnknown"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadSfcAltBrStart"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadSfcInitStep"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadSfcInitStepNot"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadSfcParBrStart"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadStrLitInCall"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadTimeLit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadUndefVariaRef"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadUnknownDatatype"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadUntermCmt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "BadWriteToConst"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "Ctrl"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlAcyc"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlAcycB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlC"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlCountMatch"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlD"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlDateMatch"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlDef"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlDefParam"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlE"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlF"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlFullArity"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlG"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlH"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlI"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlInitFirst"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlInst"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlOrdName"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlSingleInit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlTypedXfer"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "CtrlWithInit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeArithPrec"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeBareDurZero"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeCaseInsens"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeCmtInEq"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeConstStrSetGet"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeCoordInvarTail"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeDeepNestCmts"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeDurInParamMap"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeDurVarFmt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeElsifExpr"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeEmptyCodeBlk"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeEmptyRecType"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeFrameModInvoc"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeGlobalParamMap"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeKwPrefixed"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeLegacySeqNo"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeMinSeq"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeModDefNoTrail"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeModOpt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeNegDurVal"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeOldNewOnDotted"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeOpSaveAndState"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeQuotedIdentMax"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeScanGrpCl"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSeqAlt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSeqBrk"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSeqForkMulti"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSeqPar"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSimpleModType"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSubSeqDef"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeSubSeqTrans"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeTermSeqStep"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeTimeValInit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "EdgeUnicodeIdents"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "LoopA"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "LoopB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "Prog"
      Directory "probes"
      MainProgram True )
   Program
    ( Name "ProgBadDep"
      Directory "probes"
      MainProgram False )
   Library
    ( Name "PumpLib"
      Directory "probes" )
   Library
    ( Name "UnusedLib"
      Directory "probes" )
   Program
    ( Name "ValidAllDatatypes"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidBuiltinCalls"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidComprFull"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidComprSeqBasic"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidCoordInVar"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidCtrlFlow"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidDefInitOnRec"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidDurAndTime"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidGraphicsObj"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidGraphObj"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidGraphObjB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidGraphObjEnabl"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidInteract"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidInteractEnabl"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidMinProg"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidMultiEqBlk"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidMultiModDef"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidMultiTypedef"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidNestSubmods"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidOldNewOnState"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidOpenSeqSeq"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidQuotedIdents"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidRecTypeAcc"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSeqAlt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSeqBasic"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSeqPar"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSfcUnnamed"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSubmodParams"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSubseqBlk"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSubSeqTrans"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidSubSeqTransB"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidUnComprFull"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ValidVariaMods"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolAnyTypeFld"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolBoolToReal"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolConstNoInit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolCycle"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolDateShift"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolDefScalLocVar"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolExtraObj"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolInitAfterStep"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolIntCond"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolIntFromBool"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolMissMap"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolOldOnNonState"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolOpSaveStr"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolRealVsBool"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolSecInit"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolSelfInst"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolSeqReset"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolStateInt"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolStepAcc"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolStrArg"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolTooDeep"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolUndefBind"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolUnused"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolVarGroup"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolVarOff"
      Directory "probes"
      MainProgram False )
   Program
    ( Name "ViolVarOn"
      Directory "probes"
      MainProgram False ) )
Screen
 ( Attributes
    ( ModuleName On
      Coordinates On )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "AnyTypeLocVar"
      Position ( 0.050000 0.050000 0.102000 0.133000 )
      Transform ( 0.076 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "AnyTypeParam"
      Position ( 0.106000 0.050000 0.158000 0.133000 )
      Transform ( 0.132 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadBareDurStr"
      Position ( 0.162000 0.050000 0.214000 0.133000 )
      Transform ( 0.188 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadBareTimeStr"
      Position ( 0.218000 0.050000 0.270000 0.133000 )
      Transform ( 0.244 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadBuiltinDatatype"
      Position ( 0.274000 0.050000 0.326000 0.133000 )
      Transform ( 0.3 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadBuiltinOutArg"
      Position ( 0.330000 0.050000 0.382000 0.133000 )
      Transform ( 0.356 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadBuiltinWrong"
      Position ( 0.386000 0.050000 0.438000 0.133000 )
      Transform ( 0.412 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadConsecSeqSteps"
      Position ( 0.442000 0.050000 0.494000 0.133000 )
      Transform ( 0.468 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadConstVarAs"
      Position ( 0.498000 0.050000 0.550000 0.133000 )
      Transform ( 0.524 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadCrossMod"
      Position ( 0.554000 0.050000 0.606000 0.133000 )
      Transform ( 0.58 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDatatypeShadows"
      Position ( 0.610000 0.050000 0.662000 0.133000 )
      Transform ( 0.636 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupDatatypeName"
      Position ( 0.666000 0.050000 0.718000 0.133000 )
      Transform ( 0.692 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupModTypeName"
      Position ( 0.722000 0.050000 0.774000 0.133000 )
      Transform ( 0.748 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupRecFldName"
      Position ( 0.778000 0.050000 0.830000 0.133000 )
      Transform ( 0.804 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupSfcElemNames"
      Position ( 0.834000 0.050000 0.886000 0.133000 )
      Transform ( 0.86 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupSibSubmods"
      Position ( 0.890000 0.050000 0.942000 0.133000 )
      Transform ( 0.916 0.0915 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDupVariaNames"
      Position ( 0.050000 0.138000 0.102000 0.221000 )
      Transform ( 0.076 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadDurLit"
      Position ( 0.106000 0.138000 0.158000 0.221000 )
      Transform ( 0.132 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadEncodingStress"
      Position ( 0.162000 0.138000 0.214000 0.221000 )
      Transform ( 0.188 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadFreeCmtInMod"
      Position ( 0.218000 0.138000 0.270000 0.221000 )
      Transform ( 0.244 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadGraphObjDouble"
      Position ( 0.274000 0.138000 0.326000 0.221000 )
      Transform ( 0.3 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadInitValType"
      Position ( 0.330000 0.138000 0.382000 0.221000 )
      Transform ( 0.356 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadMalformed"
      Position ( 0.386000 0.138000 0.438000 0.221000 )
      Transform ( 0.412 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadModCodeWithMod"
      Position ( 0.442000 0.138000 0.494000 0.221000 )
      Transform ( 0.468 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadNotSattLine"
      Position ( 0.498000 0.138000 0.550000 0.221000 )
      Transform ( 0.524 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadOldNewOnNon"
      Position ( 0.554000 0.138000 0.606000 0.221000 )
      Transform ( 0.58 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadOldNewOnNonB"
      Position ( 0.610000 0.138000 0.662000 0.221000 )
      Transform ( 0.636 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadOversizeInput"
      Position ( 0.666000 0.138000 0.718000 0.221000 )
      Transform ( 0.692 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadSeqForkUnknown"
      Position ( 0.722000 0.138000 0.774000 0.221000 )
      Transform ( 0.748 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadSfcAltBrStart"
      Position ( 0.778000 0.138000 0.830000 0.221000 )
      Transform ( 0.804 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadSfcInitStep"
      Position ( 0.834000 0.138000 0.886000 0.221000 )
      Transform ( 0.86 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadSfcInitStepNot"
      Position ( 0.890000 0.138000 0.942000 0.221000 )
      Transform ( 0.916 0.1795 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadSfcParBrStart"
      Position ( 0.050000 0.226000 0.102000 0.309000 )
      Transform ( 0.076 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadStrLitInCall"
      Position ( 0.106000 0.226000 0.158000 0.309000 )
      Transform ( 0.132 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadTimeLit"
      Position ( 0.162000 0.226000 0.214000 0.309000 )
      Transform ( 0.188 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadUndefVariaRef"
      Position ( 0.218000 0.226000 0.270000 0.309000 )
      Transform ( 0.244 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadUnknownDatatype"
      Position ( 0.274000 0.226000 0.326000 0.309000 )
      Transform ( 0.3 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadUntermCmt"
      Position ( 0.330000 0.226000 0.382000 0.309000 )
      Transform ( 0.356 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "BadWriteToConst"
      Position ( 0.386000 0.226000 0.438000 0.309000 )
      Transform ( 0.412 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "Ctrl"
      Position ( 0.442000 0.226000 0.494000 0.309000 )
      Transform ( 0.468 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlAcyc"
      Position ( 0.498000 0.226000 0.550000 0.309000 )
      Transform ( 0.524 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlAcycB"
      Position ( 0.554000 0.226000 0.606000 0.309000 )
      Transform ( 0.58 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlB"
      Position ( 0.610000 0.226000 0.662000 0.309000 )
      Transform ( 0.636 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlC"
      Position ( 0.666000 0.226000 0.718000 0.309000 )
      Transform ( 0.692 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlCountMatch"
      Position ( 0.722000 0.226000 0.774000 0.309000 )
      Transform ( 0.748 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlD"
      Position ( 0.778000 0.226000 0.830000 0.309000 )
      Transform ( 0.804 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlDateMatch"
      Position ( 0.834000 0.226000 0.886000 0.309000 )
      Transform ( 0.86 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlDef"
      Position ( 0.890000 0.226000 0.942000 0.309000 )
      Transform ( 0.916 0.2675 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlDefParam"
      Position ( 0.050000 0.314000 0.102000 0.397000 )
      Transform ( 0.076 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlE"
      Position ( 0.106000 0.314000 0.158000 0.397000 )
      Transform ( 0.132 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlF"
      Position ( 0.162000 0.314000 0.214000 0.397000 )
      Transform ( 0.188 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlFullArity"
      Position ( 0.218000 0.314000 0.270000 0.397000 )
      Transform ( 0.244 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlG"
      Position ( 0.274000 0.314000 0.326000 0.397000 )
      Transform ( 0.3 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlH"
      Position ( 0.330000 0.314000 0.382000 0.397000 )
      Transform ( 0.356 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlI"
      Position ( 0.386000 0.314000 0.438000 0.397000 )
      Transform ( 0.412 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlInitFirst"
      Position ( 0.442000 0.314000 0.494000 0.397000 )
      Transform ( 0.468 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlInst"
      Position ( 0.498000 0.314000 0.550000 0.397000 )
      Transform ( 0.524 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlOrdName"
      Position ( 0.554000 0.314000 0.606000 0.397000 )
      Transform ( 0.58 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlSingleInit"
      Position ( 0.610000 0.314000 0.662000 0.397000 )
      Transform ( 0.636 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlTypedXfer"
      Position ( 0.666000 0.314000 0.718000 0.397000 )
      Transform ( 0.692 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "CtrlWithInit"
      Position ( 0.722000 0.314000 0.774000 0.397000 )
      Transform ( 0.748 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeArithPrec"
      Position ( 0.778000 0.314000 0.830000 0.397000 )
      Transform ( 0.804 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeBareDurZero"
      Position ( 0.834000 0.314000 0.886000 0.397000 )
      Transform ( 0.86 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeCaseInsens"
      Position ( 0.890000 0.314000 0.942000 0.397000 )
      Transform ( 0.916 0.3555 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeCmtInEq"
      Position ( 0.050000 0.402000 0.102000 0.485000 )
      Transform ( 0.076 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeConstStrSetGet"
      Position ( 0.106000 0.402000 0.158000 0.485000 )
      Transform ( 0.132 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeCoordInvarTail"
      Position ( 0.162000 0.402000 0.214000 0.485000 )
      Transform ( 0.188 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeDeepNestCmts"
      Position ( 0.218000 0.402000 0.270000 0.485000 )
      Transform ( 0.244 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeDurInParamMap"
      Position ( 0.274000 0.402000 0.326000 0.485000 )
      Transform ( 0.3 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeDurVarFmt"
      Position ( 0.330000 0.402000 0.382000 0.485000 )
      Transform ( 0.356 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeElsifExpr"
      Position ( 0.386000 0.402000 0.438000 0.485000 )
      Transform ( 0.412 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeEmptyCodeBlk"
      Position ( 0.442000 0.402000 0.494000 0.485000 )
      Transform ( 0.468 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeEmptyRecType"
      Position ( 0.498000 0.402000 0.550000 0.485000 )
      Transform ( 0.524 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeFrameModInvoc"
      Position ( 0.554000 0.402000 0.606000 0.485000 )
      Transform ( 0.58 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeGlobalParamMap"
      Position ( 0.610000 0.402000 0.662000 0.485000 )
      Transform ( 0.636 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeKwPrefixed"
      Position ( 0.666000 0.402000 0.718000 0.485000 )
      Transform ( 0.692 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeLegacySeqNo"
      Position ( 0.722000 0.402000 0.774000 0.485000 )
      Transform ( 0.748 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeMinSeq"
      Position ( 0.778000 0.402000 0.830000 0.485000 )
      Transform ( 0.804 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeModDefNoTrail"
      Position ( 0.834000 0.402000 0.886000 0.485000 )
      Transform ( 0.86 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeModOpt"
      Position ( 0.890000 0.402000 0.942000 0.485000 )
      Transform ( 0.916 0.4435 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeNegDurVal"
      Position ( 0.050000 0.490000 0.102000 0.573000 )
      Transform ( 0.076 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeOldNewOnDotted"
      Position ( 0.106000 0.490000 0.158000 0.573000 )
      Transform ( 0.132 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeOpSaveAndState"
      Position ( 0.162000 0.490000 0.214000 0.573000 )
      Transform ( 0.188 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeQuotedIdentMax"
      Position ( 0.218000 0.490000 0.270000 0.573000 )
      Transform ( 0.244 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeScanGrpCl"
      Position ( 0.274000 0.490000 0.326000 0.573000 )
      Transform ( 0.3 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSeqAlt"
      Position ( 0.330000 0.490000 0.382000 0.573000 )
      Transform ( 0.356 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSeqBrk"
      Position ( 0.386000 0.490000 0.438000 0.573000 )
      Transform ( 0.412 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSeqForkMulti"
      Position ( 0.442000 0.490000 0.494000 0.573000 )
      Transform ( 0.468 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSeqPar"
      Position ( 0.498000 0.490000 0.550000 0.573000 )
      Transform ( 0.524 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSimpleModType"
      Position ( 0.554000 0.490000 0.606000 0.573000 )
      Transform ( 0.58 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSubSeqDef"
      Position ( 0.610000 0.490000 0.662000 0.573000 )
      Transform ( 0.636 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeSubSeqTrans"
      Position ( 0.666000 0.490000 0.718000 0.573000 )
      Transform ( 0.692 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeTermSeqStep"
      Position ( 0.722000 0.490000 0.774000 0.573000 )
      Transform ( 0.748 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeTimeValInit"
      Position ( 0.778000 0.490000 0.830000 0.573000 )
      Transform ( 0.804 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "EdgeUnicodeIdents"
      Position ( 0.834000 0.490000 0.886000 0.573000 )
      Transform ( 0.86 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "LoopA"
      Position ( 0.890000 0.490000 0.942000 0.573000 )
      Transform ( 0.916 0.5315 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "LoopB"
      Position ( 0.050000 0.578000 0.102000 0.661000 )
      Transform ( 0.076 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "Prog"
      Position ( 0.106000 0.578000 0.158000 0.661000 )
      Transform ( 0.132 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ProgBadDep"
      Position ( 0.162000 0.578000 0.214000 0.661000 )
      Transform ( 0.188 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidAllDatatypes"
      Position ( 0.218000 0.578000 0.270000 0.661000 )
      Transform ( 0.244 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidBuiltinCalls"
      Position ( 0.274000 0.578000 0.326000 0.661000 )
      Transform ( 0.3 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidComprFull"
      Position ( 0.330000 0.578000 0.382000 0.661000 )
      Transform ( 0.356 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidComprSeqBasic"
      Position ( 0.386000 0.578000 0.438000 0.661000 )
      Transform ( 0.412 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidCoordInVar"
      Position ( 0.442000 0.578000 0.494000 0.661000 )
      Transform ( 0.468 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidCtrlFlow"
      Position ( 0.498000 0.578000 0.550000 0.661000 )
      Transform ( 0.524 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidDefInitOnRec"
      Position ( 0.554000 0.578000 0.606000 0.661000 )
      Transform ( 0.58 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidDurAndTime"
      Position ( 0.610000 0.578000 0.662000 0.661000 )
      Transform ( 0.636 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidGraphicsObj"
      Position ( 0.666000 0.578000 0.718000 0.661000 )
      Transform ( 0.692 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidGraphObj"
      Position ( 0.722000 0.578000 0.774000 0.661000 )
      Transform ( 0.748 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidGraphObjB"
      Position ( 0.778000 0.578000 0.830000 0.661000 )
      Transform ( 0.804 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidGraphObjEnabl"
      Position ( 0.834000 0.578000 0.886000 0.661000 )
      Transform ( 0.86 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidInteract"
      Position ( 0.890000 0.578000 0.942000 0.661000 )
      Transform ( 0.916 0.6195 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidInteractEnabl"
      Position ( 0.050000 0.666000 0.102000 0.749000 )
      Transform ( 0.076 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidMinProg"
      Position ( 0.106000 0.666000 0.158000 0.749000 )
      Transform ( 0.132 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidMultiEqBlk"
      Position ( 0.162000 0.666000 0.214000 0.749000 )
      Transform ( 0.188 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidMultiModDef"
      Position ( 0.218000 0.666000 0.270000 0.749000 )
      Transform ( 0.244 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidMultiTypedef"
      Position ( 0.274000 0.666000 0.326000 0.749000 )
      Transform ( 0.3 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidNestSubmods"
      Position ( 0.330000 0.666000 0.382000 0.749000 )
      Transform ( 0.356 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidOldNewOnState"
      Position ( 0.386000 0.666000 0.438000 0.749000 )
      Transform ( 0.412 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidOpenSeqSeq"
      Position ( 0.442000 0.666000 0.494000 0.749000 )
      Transform ( 0.468 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidQuotedIdents"
      Position ( 0.498000 0.666000 0.550000 0.749000 )
      Transform ( 0.524 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidRecTypeAcc"
      Position ( 0.554000 0.666000 0.606000 0.749000 )
      Transform ( 0.58 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSeqAlt"
      Position ( 0.610000 0.666000 0.662000 0.749000 )
      Transform ( 0.636 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSeqBasic"
      Position ( 0.666000 0.666000 0.718000 0.749000 )
      Transform ( 0.692 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSeqPar"
      Position ( 0.722000 0.666000 0.774000 0.749000 )
      Transform ( 0.748 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSfcUnnamed"
      Position ( 0.778000 0.666000 0.830000 0.749000 )
      Transform ( 0.804 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSubmodParams"
      Position ( 0.834000 0.666000 0.886000 0.749000 )
      Transform ( 0.86 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSubseqBlk"
      Position ( 0.890000 0.666000 0.942000 0.749000 )
      Transform ( 0.916 0.7075 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSubSeqTrans"
      Position ( 0.050000 0.754000 0.102000 0.837000 )
      Transform ( 0.076 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidSubSeqTransB"
      Position ( 0.106000 0.754000 0.158000 0.837000 )
      Transform ( 0.132 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidUnComprFull"
      Position ( 0.162000 0.754000 0.214000 0.837000 )
      Transform ( 0.188 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ValidVariaMods"
      Position ( 0.218000 0.754000 0.270000 0.837000 )
      Transform ( 0.244 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolAnyTypeFld"
      Position ( 0.274000 0.754000 0.326000 0.837000 )
      Transform ( 0.3 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolBoolToReal"
      Position ( 0.330000 0.754000 0.382000 0.837000 )
      Transform ( 0.356 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolConstNoInit"
      Position ( 0.386000 0.754000 0.438000 0.837000 )
      Transform ( 0.412 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolCycle"
      Position ( 0.442000 0.754000 0.494000 0.837000 )
      Transform ( 0.468 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolDateShift"
      Position ( 0.498000 0.754000 0.550000 0.837000 )
      Transform ( 0.524 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolDefScalLocVar"
      Position ( 0.554000 0.754000 0.606000 0.837000 )
      Transform ( 0.58 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolExtraObj"
      Position ( 0.610000 0.754000 0.662000 0.837000 )
      Transform ( 0.636 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolInitAfterStep"
      Position ( 0.666000 0.754000 0.718000 0.837000 )
      Transform ( 0.692 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolIntCond"
      Position ( 0.722000 0.754000 0.774000 0.837000 )
      Transform ( 0.748 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolIntFromBool"
      Position ( 0.778000 0.754000 0.830000 0.837000 )
      Transform ( 0.804 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolMissMap"
      Position ( 0.834000 0.754000 0.886000 0.837000 )
      Transform ( 0.86 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolOldOnNonState"
      Position ( 0.890000 0.754000 0.942000 0.837000 )
      Transform ( 0.916 0.7955 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolOpSaveStr"
      Position ( 0.050000 0.842000 0.102000 0.925000 )
      Transform ( 0.076 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolRealVsBool"
      Position ( 0.106000 0.842000 0.158000 0.925000 )
      Transform ( 0.132 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolSecInit"
      Position ( 0.162000 0.842000 0.214000 0.925000 )
      Transform ( 0.188 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolSelfInst"
      Position ( 0.218000 0.842000 0.270000 0.925000 )
      Transform ( 0.244 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolSeqReset"
      Position ( 0.274000 0.842000 0.326000 0.925000 )
      Transform ( 0.3 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolStateInt"
      Position ( 0.330000 0.842000 0.382000 0.925000 )
      Transform ( 0.356 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolStepAcc"
      Position ( 0.386000 0.842000 0.438000 0.925000 )
      Transform ( 0.412 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolStrArg"
      Position ( 0.442000 0.842000 0.494000 0.925000 )
      Transform ( 0.468 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolTooDeep"
      Position ( 0.498000 0.842000 0.550000 0.925000 )
      Transform ( 0.524 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolUndefBind"
      Position ( 0.554000 0.842000 0.606000 0.925000 )
      Transform ( 0.58 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolUnused"
      Position ( 0.610000 0.842000 0.662000 0.925000 )
      Transform ( 0.636 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolVarGroup"
      Position ( 0.666000 0.842000 0.718000 0.925000 )
      Transform ( 0.692 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolVarOff"
      Position ( 0.722000 0.842000 0.774000 0.925000 )
      Transform ( 0.748 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Content "ViolVarOn"
      Position ( 0.778000 0.842000 0.830000 0.925000 )
      Transform ( 0.804 0.8835 0.107073138871261 ) )
   Window
    ( Attributes
       ( WindowState Normal
         ShowTools On
         Visible True
         
         FixPosition False )
      Position ( 0.218000 0.050000 0.270000 0.133000 )
      Transform ( 0.244 0.0915 1.30917024612427 ) ) )
ColorTable
 ( ColorModel HLS
   100 ( Blink ( OnColor 12
         OffColor 0
         OnTime 0.8
         OffTime 0.2
         Phase 0.1 ) )
   101 ( Blink ( OnColor 12
         OffColor 0
         OnTime 0.25
         OffTime 0.25
         Phase 0.25 ) )
   102 ( Blink ( OnColor 45
         OffColor 2
         OnTime 0.8
         OffTime 0.4
         Phase 1.2 ) )
   103 ( Blink ( OnColor 32
         OffColor 40
         OnTime 0.375
         OffTime 0.375
         Phase 0.25 ) )
   104 ( Blink ( OnColor 32
         OffColor 5
         OnTime 0.8
         OffTime 0.4
         Phase 0.0 ) )
   105 ( Blink ( OnColor 32
         OffColor 51
         OnTime 1.5
         OffTime 0.5
         Phase 0.0 ) )
   111 ( 0.0 0.0 0.0 )
   112 ( 35.0 0.5 1.0 )
   113 ( 120.0 0.35 1.0 )
   114 ( 200.0 0.35 1.0 ) )
